sudo: false

jobs:
  include:
    - script:
      - docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD"
      - docker build --quiet --file Dockerfile --tag $TRAVIS_REPO_SLUG:$TRAVIS_COMMIT .
      - docker push $DOCKER_USERNAME/docker-android
